---
- name: Install Apache Web Server
  hosts: web_server
  become: true
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: present

    - name: Start Apache service
      service:
        name: httpd
        state: started
        enabled: true

    - name: Install firewall
      yum:
        name: firewalld
        state: present
      
    - name: Start firewall service
      service:
        name: firewalld
        state: started
        enabled: true

    - name: open firewall port 80
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes

    - name: restart firewall
      service:
        name: firewalld
        state: restarted

    - name: Ensure Apache is running
      wait_for:
        port: 80
        delay: 10
        timeout: 30